spring:
  application:
    name: community-app
  datasource:
    url: jdbc:mysql://localhost:3306/community_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: me.sisyphusj.**
  mapper-locations: classpath:mapper/*.xml

server:
  servlet:
    jsp:
      init-parameters:
        development=true: true
    session:
      timeout: 800
