spring:
  application:
    name: community-app
  datasource:
    url: jdbc:mysql://localhost:3306/community_db
    username: ENC(ZUy7P5OfC43x70qj1DllMg==)
    password: ENC(db3q+EGZEB3Ifvgudxip9Q==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(NkNgVsTYnEMyZRcBevvY74OGJSrCgJ259S6y8M2cgWUX6EnmAE3s8f51AsOc+bby)
            client-secret: ENC(pMCqarZKWtUbUTwvNcvRsxmDo1jEHmPL7Y94Y4QvbQEhtY1saqwJLAnNlbVYOKWq)
            client-authentication-method: client_secret_post
            redirect-uri: "http://localhost/auth/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
          google:
            client-id: ENC(rZOAmCwiaQeiKi/CB/Au0+OgRDbuj3tPpGiAhhVn8YfFpu4EUpgw6QAxIMtpT8D5o9GVxSfhmVGGtsmz6d1TbKN5TEzYh/i3SLADIv8Yuzo=)
            client-secret: ENC(evEQO1Yzscf5TeXdJuw/Pn7X0VSLjXbZEww+X8LdD2atJq6eS4IUG6Ljf1fsNtkc)
            scope: profile
            redirect-uri: http://localhost/auth/oauth2/code/google
          naver:
            client-id: ENC(igDX+k3cuzTtsWmbg8X+1XoMgJ2TeFh9eetbJ6HPQK0=)
            client-secret: ENC(Mt4WC7N2f8HgVV8lExGYvBWu4PwPVz3w)
            scope: name
            client-name: Naver
            redirect-uri: "http://localhost/auth/oauth2/code/naver"
            authorization-grant-type: authorization_code
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id




mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: me.sisyphusj.**
  mapper-locations: classpath:mapper/*.xml

server:
  servlet:
    jsp:
      init-parameters:
        development: true
    session:
      timeout: 800
  port: 80
